# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  businessdomain:
    image: bussinesslogic-dev
    build:
      context: .
      dockerfile: BusinessDomain/BusinessLogic.Entry/Dockerfile
    environment:
      - ConnectionStrings__Default=Server=businessdomaindb;Port=3307;Database=BusinessLogicDb;Uid=root;Pwd=2510203121;
      - ConnectionStrings__Redis=redis:6379
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    ports:
      - 5001:5001
    depends_on:
      - businessdomaindb
      - seq
    healthcheck:
      test: ["CMD","curl","-f","http://businessdomaindb:3307",";","CMD","curl","-f","http://seq:5431"]
      timeout: 1m30s
      interval: 20s
      retries: 5
      start_period: 40s

  businessdomaindb:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=2510203121
      - MYSQL_DATABASE=BusinessLogicDb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=2510203121
      - MYSQL_TCP_PORT=3307

    volumes:
      - businessdbvolume:/var/lib/mysql
    ports:
      - 3307:3307

  seq:
    image: datalust/seq:latest
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
volumes:
  businessdbvolume:

